- name: Install logrotate and zstd
  dnf:
    state: present
    name:
      - logrotate
      - zstd
  register: install_logrotate_and_zstd_result
  retries: 30
  until: install_logrotate_and_zstd_result is succeeded

- name: Ensure directory exists
  file:
    path: "/etc/systemd/system/logrotate.timer.d"
    state: directory
    mode: 0755

- name: Schedule logrotate hourly
  template:
    src: logrotate.override
    dest: /etc/systemd/system/logrotate.timer.d/override.conf
    mode: 0644

- name: Install syslog logroate config
  template:
    src: syslog.logrotate
    dest: /etc/logrotate.d/rsyslog
    mode: 0644

- name: Reload logrotate
  service:
    name: logrotate.timer
    state: restarted
