- name: Install pushprox
  dnf:
    name: pushprox-client
    state: latest
  register: install_pushprox_result
  retries: 30
  until: install_pushprox_result is succeeded

- name: Configure proxy
  template:
    src: pushprox-env
    dest: /etc/default/pushprox-client
    force: yes

- name: Enable pushprox service
  service:
    name: pushprox-client
    enabled: yes
    state: restarted
