- name: Install varnish-exporter
  dnf:
    name: varnish-exporter
    state: latest
  register: install_varnish_exporter_result
  retries: 30
  until: install_varnish_exporter_result is succeeded

- name: Enable varnish-exporter service
  service:
    name: varnish-exporter
    enabled: yes
    state: started
