---
- name: install tinyproxy
  yum:
    name: tinyproxy
    state: latest
  register: install_tinyproxy_result
  retries: 30
  until: install_tinyproxy_result is succeeded

- name: configure tinyproxy
  template:
    src: tinyproxy.conf.j2
    dest: /etc/tinyproxy/tinyproxy.conf
  notify: restart tinyproxy

- name: enable and start tinyproxy service
  service:
    name: tinyproxy
    state: started
    enabled: yes
