- name: Install geolite2 pakcages
  dnf:
    name: "{{ packages }}"
  register: install_geolite2_pakcages_result
  retries: 30
  until: install_geolite2_pakcages_result is succeeded
  vars:
    packages:
    - geoipupdate
    - geoipupdate-cron
    state: latest

- name: Install geoupdate configuration
  template:
    src: GeoIP.conf.j2
    dest: /etc/GeoIP.conf

- name: Update geolite2 databases
  shell: geoipupdate
