- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - role: cs.aws-region-facts
    - role: cs.aws-logs-slack
      when: aws_logs_slack_notifications
    - role: cs.aws-logs-retention
