
- hosts: localhost
  connection: local
  roles:
    - role: cs.aws-region-facts
    - role: cs.aws-rds-facts
    - role: cs.aws-node-facts
    - role: cs.aws-autoscaling-facts

  tasks:
    - name: Scale down all App Node ASGs
      when: stop_asg
      block:
        - name: Get App Node Auto Scaling Groups
          amazon.aws.autoscaling_group_info:
            region: "{{ aws_region }}"
            tags: "{{ aws_tags_base | combine(aws_tags_role_app) }}"
          register: stop_asg_facts

        - name: Scale down ASG to zero
          amazon.aws.autoscaling_group:
            name: "{{ item.name }}"
            region: "{{ aws_region }}"
            state: present
            desired_capacity: 0
            min_size: 0
            wait_for_instances: no
          with_items: "{{ stop_asgs }}"
          vars:
            stop_asgs: "{{ stop_asg_facts | json_query('results[].{ name: auto_scaling_group_name }') }}"

    - name: Stop standalone EC2 instances
      when: stop_ec2
      amazon.aws.ec2_instance:
        instance_ids: "{{ item.instance_id }}"
        region: "{{ aws_region }}"
        state: stopped
        wait: no
      with_items:
        - "{{ aws_persistent_node_instance }}"
        - "{{ aws_varnish_node_instance }}"

    - name: Scale down all App and PIO Node ASGs
      when: stop_asg
      amazon.aws.autoscaling_group:
        name: "{{ item.auto_scaling_group_name }}"
        region: "{{ aws_region }}"
        state: present
        desired_capacity: 0
        min_size: 0
        wait_for_instances: no
      with_items:
        - "{{ aws_autoscaling_app }}"
        - "{{ aws_autoscaling_app_extra }}"
        - "{{ aws_autoscaling_app_pio }}"

    - name: Stop Aurora RDS cluster
      ansible.builtin.command:
        argv:
          - aws
          - rds
          - stop-db-cluster
          - --db-cluster-identifier
          - "{{ aws_rds_cluster.db_cluster_identifier }}"
          - --region
          - "{{ aws_region }}"
      changed_when: true
      when:
        - stop_rds
        - aws_rds_cluster is defined
        - aws_rds_cluster.status == "available"

    - name: Stop standalone RDS instance
      rds_instance:
        state: stopped
        region: "{{ aws_region }}"
        db_instance_identifier: "{{ aws_rds_instance.db_instance_identifier }}"
      when:
        - stop_rds
        - aws_rds_instance is defined
        - aws_rds_instance.db_cluster_identifier is not defined or not aws_rds_instance.db_cluster_identifier

  vars:
    stop: yes
    stop_ec2: "{{ stop }}"
    stop_asg: "{{ stop }}"
    stop_rds: "{{ stop }}"
