- name: Install versionlock plugin
  dnf:
    name:
      - dnf-plugin-versionlock
    state: latest

- name: Install dnf versionlock
  blockinfile:
    create: yes
    mode: 0644
    path: /etc/dnf/plugins/versionlock.list
    marker: "# {mark} {{ node_name }}"
    block: "{{ lookup('template', 'versionlock.list.j2') }}"
