- name: Ensure EPEL repo release package is installed and up-to-date
  dnf:
    name: "{{ repo_epel_package_name }}"

- name: Ensure EPEL is enabled
  command: yum-config-manager --enable epel

- name: Ensure EPEL is enabled
  command: yum-config-manager --enable epel-testing
  when: repo_epel_testing | bool

- name: Ensure EPEL is disabled
  command: yum-config-manager --disable epel-testing
  when: not repo_epel_testing | bool

- name: Ensure crb is enabled
  command: yum-config-manager --enable crb
