- name: Fetch existing log groups only for selected region
  shell: "aws logs describe-log-groups --region={{ aws_region }}"
  register: aws_log_rentention_describe
  changed_when: no

- name: Get log groups with no retention in selected region
  set_fact:
    data:
      groups: "{{ (aws_log_rentention_describe.stdout | from_json).logGroups | json_query('[?!retentionInDays].logGroupName') }}"
      region: "{{ aws_region }}"
  when: aws_log_rentention_describe.stdout is defined
  register: aws_log_retention_groups

- name: Set log retention for groups without retention
  shell: "aws logs put-retention-policy --log-group-name={{ item }} --retention-in-days=7 --region={{ aws_region }}"
  loop: "{{ aws_log_retention_groups.ansible_facts.data.groups }}"
