- name: Get current cloudfront distribution config
  ansible.builtin.command:
    argv:
      - aws
      - cloudfront
      - get-distribution
      - --id
      - "{{ aws_cloudfront_distribution_id }}"
      - --output
      - json
  register: cloudfront_current_distribution_cmd
  changed_when: false
  when: aws_cloudfront_distribution_id is defined

- name: Resolve cloudfront origin domain name
  ansible.builtin.set_fact:
    cloudfront_origin_domain_name: >-
      {{
        (
          lb_domain is defined and lb_domain | length > 0
        )
        | ternary(
            lb_domain,
            (
              aws_cloudfront_distribution_id is defined
            )
            | ternary(
                (
                  (
                    cloudfront_current_distribution_cmd.stdout | default('{}') | from_json
                  ).Distribution.DistributionConfig.Origins.Items
                  | default([])
                  | selectattr('OriginPath', 'equalto', '/media')
                  | map(attribute='DomainName')
                  | first
                  | default(
                      (
                        (
                          cloudfront_current_distribution_cmd.stdout | default('{}') | from_json
                        ).Distribution.DistributionConfig.Origins.Items
                        | default([])
                        | map(attribute='DomainName')
                        | first
                      ),
                      true
                    )
                  | default(magento_hostname, true)
                ),
                magento_hostname
              )
          )
      }}

- name: Create temporary distribution config build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: aws_cloudfront_distribution_temp_dir

- name: Build cloudfront distribution config
  ansible.builtin.template:
    src: lb-media-distribution-config.json
    dest: "{{ aws_cloudfront_distribution_temp_dir.path }}/config.json"
    mode: "0600"

- name: Build cloudfront tag config
  ansible.builtin.template:
    src: cloudfront-tags.json
    dest: "{{ aws_cloudfront_distribution_temp_dir.path }}/tags.json"
    mode: "0600"

- name: Create cloudfront distribution
  ansible.builtin.command:
    argv:
      - aws
      - cloudfront
      - create-distribution
      - --distribution-config=file://{{ aws_cloudfront_distribution_temp_dir.path }}/config.json
  when: aws_cloudfront_distribution is not defined
  register: aws_cloudfront_create_distribution_cmd
  changed_when: true

- name: Update cloudfront distribution
  ansible.builtin.command:
    argv:
      - aws
      - cloudfront
      - update-distribution
      - --distribution-config=file://{{ aws_cloudfront_distribution_temp_dir.path }}/config.json
      - --id={{ aws_cloudfront_distribution.Id }}
      - --if-match={{ aws_cloudfront_distribution.ETag }}
  when:
    - aws_cloudfront_distribution is defined
    - aws_cloudfront_distribution.Id is defined
    - aws_cloudfront_distribution.ETag is defined
  register: aws_cloudfront_update_distribution_cmd
  changed_when: true

- name: Set cloudfront distribution facts from create result
  ansible.builtin.set_fact:
    aws_cloudfront_distribution_id: "{{ (aws_cloudfront_create_distribution_cmd.stdout | from_json).Distribution.Id }}"
    aws_cloudfront_distribution_arn: "{{ (aws_cloudfront_create_distribution_cmd.stdout | from_json).Distribution.ARN }}"
  when:
    - aws_cloudfront_create_distribution_cmd is defined
    - "'rc' in aws_cloudfront_create_distribution_cmd"
    - aws_cloudfront_create_distribution_cmd.rc == 0

- name: Set cloudfront distribution arn from update result
  ansible.builtin.set_fact:
    aws_cloudfront_distribution_arn: "{{ (aws_cloudfront_update_distribution_cmd.stdout | from_json).Distribution.ARN }}"
  when:
    - aws_cloudfront_update_distribution_cmd is defined
    - "'rc' in aws_cloudfront_update_distribution_cmd"
    - aws_cloudfront_update_distribution_cmd.rc == 0

- name: Ensure distribution arn fact exists
  ansible.builtin.set_fact:
    aws_cloudfront_distribution_arn: "{{ aws_cloudfront_distribution.ARN }}"
  when:
    - aws_cloudfront_distribution_arn is not defined
    - aws_cloudfront_distribution is defined
    - aws_cloudfront_distribution.ARN is defined

- name: Ensure distribution is tagged
  ansible.builtin.command:
    argv:
      - aws
      - cloudfront
      - tag-resource
      - --resource
      - "{{ aws_cloudfront_distribution_arn }}"
      - --tags
      - file://{{ aws_cloudfront_distribution_temp_dir.path }}/tags.json
  when: aws_cloudfront_distribution_arn is defined
  changed_when: true
