plugin: aws_ec2

strict: False

hostvars_prefix: aws_

regions: eu-central-1

filters:
  tag:Infrastructure: mageops
  instance-state-name:
    - running
    - pending

keyed_groups:
  - key: aws_tags.Name
    prefix: "node"
    separator: "_"

  - key: aws_tags.AppName
    prefix: "app"
    separator: "_"

  - key: aws_tags.AppId
    prefix: "app"
    separator: "_"

  - key: aws_tags.Role
    prefix: ""
    separator: ""

  - key: aws_tags.RoleBuilder
    prefix: "builder"
    separator: "_"

  - key: aws_tags.RoleExtra
    prefix: "extra"
    separator: "_"

  - key: aws_tags.RoleSearch
    prefix: ""
    separator: ""

  - key: aws_tags.RoleCache
    prefix: ""
    separator: ""

  - key: aws_tags.RoleHttpCache
    prefix: ""
    separator: ""

  - key: aws_tags.RoleLoadBalancer
    prefix: ""
    separator: ""

  - key: aws_tags.RoleDatabase
    prefix: ""
    separator: ""

  - key: aws_tags.RoleStorage
    prefix: ""
    separator: ""

  - key: aws_tags.RoleMessageQueue
    prefix: ""
    separator: ""

  - key: aws_tags.TraitImmutable
    prefix: ""
    separator: ""
