- name: Reload systemctl daemon
  systemd:
    daemon_reload: yes

- name: Restart {{ redis_daemon }}
  service:
    name: "{{ redis_daemon }}"
    state: restarted

- name: Restart valkey
  service:
    name: "{{ redis_daemon }}"
    state: restarted

- name: Restart valkey-sessions
  service:
    name: "{{ redis_daemon }}"
    state: restarted