---
- name: Install zram-generator
  package:
    name: zram-generator
    state: present
  become: true
  register: install_zram_generator_result
  retries: 30
  until: install_zram_generator_result is succeeded

- name: Configure zram-generator
  template:
    src: zram-generator.conf.j2
    dest: /etc/systemd/zram-generator.conf
    owner: root
    group: root
    mode: '0644'
  become: true
