- name: Install earlyoom packages
  dnf:
    name: earlyoom
    state: present
  register: install_earlyoom_packages_result
  retries: 30
  until: install_earlyoom_packages_result is succeeded

- name: Configure earlyoom
  template:
    src: earlyoom.default
    dest: /etc/default/earlyoom
    force: yes
  notify: Restart earlyoom service

- name: Start and enable earlyoom service
  service:
    name: earlyoom
    state: started
    enabled: yes
