- name: Get info about security groups
  amazon.aws.ec2_security_group_info:
    region: "{{ aws_region }}"
    filters: "{{ aws_sg_facts_filters_resolved }}"
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    aws_sg_facts_filters_resolved: >-
      {{
        aws_sg_facts_filters
        | combine({
            'vpc-id': aws_vpc_id,
            'group-name': aws_sg_facts_group_names
          })
        | combine(aws_sg_facts_tags | prefix_keys('tag:'))
      }}
  register: ec2_group_facts

- name: Set info about security groups
  set_fact:
    aws_security_groups_info: "{{ ec2_group_facts.security_groups }}"
    cacheable: yes

- name: Set info and id fact for each security group
  set_fact:
    "{{ sg_fact_name }}": "{{ sg_info }}"
    "{{ sg_fact_name }}_id": "{{ sg_info.group_id | default(omit) }}"
    cacheable: yes
  vars:
    sg_fact_name: "{{ sg_fact.key }}"
    sg_group_name: "{{ sg_fact.value }}"
    sg_info: >-
      {{
        aws_security_groups_info
        | selectattr('group_name', 'equalto', sg_group_name)
        | list
        | default([false], true)
        | first
      }}
  loop: "{{ aws_sg_facts_group_name_by_fact | dict2items }}"
  loop_control:
    loop_var: sg_fact
    label: "{{ sg_fact.key }}"
