- name: Install dnf for speedup when installing packages
  dnf:
    name:
      - dnf
      - python3-dnf-plugins-core
      - python3-dnf-plugin-cow
    state: present
  register: install_dnf_for_speedup_when_installing_packages_result
  retries: 30
  until: install_dnf_for_speedup_when_installing_packages_result is succeeded

- name: Set dnf configuration
  copy:
    src: dnf.conf
    dest: /etc/dnf/dnf.conf

- name: Switch package manager to dnf
  set_fact:
    ansible_facts:
      pkg_mgr: dnf
