- name: Download gpg cert
  command: curl -fsSL -o /etc/pki/rpm-gpg/GPG-KEY-varnish {{ repo_varnish_gpg_url }}
  args:
    creates: /etc/pki/rpm-gpg/GPG-KEY-varnish

- name: Install gpg cert
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/GPG-KEY-varnish

- name: Install varnish lts repo
  template:
    src: varnish60lts.repo
    dest: "/etc/yum.repos.d/varnish60lts.repo"
    mode: 0644
