- name: Check if architecture is supported
  fail:
    msg: "You cannot install RabbitMQ on this architecture. Supported architectures: x86_64, aarch64."
  when: ansible_facts.architecture not in ['x86_64', 'aarch64']

- name: Install rabbitmq repo
  template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    mode: "0644"

- name: Download RabbitMQ release signing key for ARM package repositories
  when: ansible_facts.architecture == 'aarch64'
  command: curl -fsSL -o /etc/pki/rpm-gpg/rabbitmq-release-signing-key.asc https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
  args:
    creates: /etc/pki/rpm-gpg/rabbitmq-release-signing-key.asc

- name: Import RabbitMQ release signing key for ARM package repositories
  when: ansible_facts.architecture == 'aarch64'
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/rabbitmq-release-signing-key.asc
