- name: "Copy varnish-purge-proxy binary file"
  command: curl -fsSL -o {{ varnish_pp_bin.path }} {{ varnish_pp_bin.src }}
  args:
    creates: "{{ varnish_pp_bin.path }}"

- name: "Set varnish-purge-proxy binary permissions"
  file:
    path: "{{ varnish_pp_bin.path }}"
    mode: "0755"
