- name: Create AWS Backup service role
  iam_role:
    assume_role_policy_document: "{{ lookup('template', 'backup_assume_policy_document.json') }}"
    name: "{{ aws_iam_role_backup }}"
    state: present
    managed_policy:
      - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
