#!/usr/bin/env bash

CONFIG_PATH="{{ magento_import_dispatcher_supervisor_config_path }}"
CONFIG_OFF_PATH="{{ magento_import_dispatcher_supervisor_config_off_path }}"
MODE="$1"

function enable() {
    echo "Enabling import dispatcher..."
    if [ -f "$CONFIG_PATH" ] ; then
        echo "Import dispatcher is already enabled."
        exit
    fi

    if [ ! -f "$CONFIG_OFF_PATH" ] ; then
        echo "Import dispatcher config file not found at $CONFIG_OFF_PATH"
        exit 2
    fi

    cp "$CONFIG_OFF_PATH" "$CONFIG_PATH"

    # Reload doesn't seem work for some reason on amilinux, fucking broken initscripts everywhere
    service supervisord restart
}

function disable() {
    echo "Disabling import dispatcher..."
    if [ ! -f "$CONFIG_PATH" ] ; then
        echo "Import dispatcher is not enabled."
        exit
    fi

    rm "$CONFIG_PATH"

    # Reload doesn't seem work for some reason on amilinux, fucking broken initscripts everywhere
    service supervisord restart
}

case "$MODE" in
    "on") enable ;;
    "off") disable ;;
    *) echo "Usage $0 [on | off]" && exit 1
esac