- name: Create S3 mount remote source dirs
  become: no
  delegate_to: localhost
  aws_s3:
    bucket: "{{ s3_mount_bucket.bucket.split(':')[0] }}"
    object: "{{ s3_mount_bucket.bucket.split(':')[1] }}"
    mode: create
    region: "{{ aws_region }}"
  when: s3_mount_bucket.bucket is search(':/')
  loop: "{{ s3_mount_buckets_resolved }}"
  loop_control:
    loop_var: s3_mount_bucket

# `findmnt` returns 1 if there are not mounts yet
- name: Get current S3 mounts
  shell: >-
    findmnt -l -n -o TARGET,SOURCE,FSTYPE |
    awk '$2 ~ /^(s3fs|goofys)#/ || $2 ~ /^{{ s3_mount_rclone_remote_name }}:/ { print $1 "\t" $2 "\t" $3 }'
  register: s3fs_current_mounts_check
  failed_when: s3fs_current_mounts_check.rc not in [0, 1]
  changed_when: false

- name: Initialize current S3 mount entry list
  set_fact:
    s3_mount_current_entries: []

- name: Parse current S3 mount entries
  set_fact:
    s3_mount_current_entries: "{{ s3_mount_current_entries + [_s3_mount_entry] }}"
  vars:
    _s3_mount_entry_parts: "{{ s3_mount_entry.split('\t') }}"
    _s3_mount_entry:
      mountpoint: "{{ _s3_mount_entry_parts[0] | realpath }}"
      source: "{{ _s3_mount_entry_parts[1] }}"
      fstype: "{{ _s3_mount_entry_parts[2] }}"
  loop: "{{ s3fs_current_mounts_check.stdout_lines }}"
  loop_control:
    loop_var: s3_mount_entry

- name: Set current S3 mountpoints
  set_fact:
    s3fs_current_mountpoints: "{{ s3_mount_current_entries | map(attribute='mountpoint') | list }}"
    s3fs_target_mountpoints: "{{ s3_mount_buckets_resolved | map(attribute='mountpoint') | map('realpath') | list }}"

- name: Unmount obsolete S3 mounts
  ansible.posix.mount:
    path: "{{ s3fs_mountpoint }}"
    state: unmounted
  when: s3fs_mountpoint not in s3fs_target_mountpoints
  loop: "{{ s3fs_current_mountpoints }}"
  loop_control:
    loop_var: s3fs_mountpoint
    label: "{{ s3fs_mountpoint }}"

- name: Remove obsolete S3 mount definitions from fstab
  ansible.posix.mount:
    path: "{{ s3fs_mountpoint }}"
    state: absent_from_fstab
  when: s3fs_mountpoint not in s3fs_target_mountpoints
  loop: "{{ s3fs_current_mountpoints }}"
  loop_control:
    loop_var: s3fs_mountpoint
    label: "{{ s3fs_mountpoint }}"

- name: Ensure target S3 mountpoint directories exist
  ansible.builtin.file:
    path: "{{ s3_mount_bucket.mountpoint }}"
    state: directory
  loop: "{{ s3_mount_buckets_resolved }}"
  loop_control:
    loop_var: s3_mount_bucket

- name: Create S3 mounts
  ansible.posix.mount:
    src: "{{ s3_mount_bucket.mount_src }}"
    path: "{{ s3_mount_bucket.mountpoint }}"
    fstype: "{{ s3_mount_fstype }}"
    opts: >-
      _netdev,allow_other,auto
      {%- if s3_mount_opts is defined and (s3_mount_opts | string | length > 0) -%}
      ,{{
        (s3_mount_opts is string)
        | ternary(s3_mount_opts, (s3_mount_opts | join(',')))
      }}
      {%- endif -%}
    state: mounted
  loop: "{{ s3_mount_buckets_resolved }}"
  loop_control:
    loop_var: s3_mount_bucket
