- import_tasks: 000-validate-config.yml
- import_tasks: 001-prepare-mount-options.yml

- import_tasks: 001-create-premount-backups.yml

- name: Setup mounts
  block:
    - include_tasks: 002-setup-mounts.yml
    - include_tasks: 003-setup-watchdog.yml
      when: s3_mount_backend == 's3fs'
    - include_tasks: 004-restore-premount-backups.yml
      when: (s3fs_premount_bind_mounts | length) > 0
  always:
    - include_tasks: 005-cleanup.yml
