[Unit]
Description=MageOps Opensearch

[Service]
LimitNOFILE={{ opensearch_syscfg_limit_nofile }}
LimitNPROC={{ opensearch_syscfg_limit_nproc }}

{% if opensearch_memlock_enable -%}
LimitMEMLOCK=infinity
{% endif %}

RestartSec=20
Restart=always

# We shall set this up later using a common role `cs.systemd-service`
# WorkingDirectory=/usr/share/opensearch
# ConfigurationDirectory=opensearch
# LogsDirectory=opensearch
# StateDirectory=opensearch
# RuntimeDirectory=opensearch