- name: Install sudo package
  dnf:
    name: sudo
  register: install_sudo_package_result
  retries: 30
  until: install_sudo_package_result is succeeded

- name: Add superuser group
  group:
    name: wheel
    state: present

- name: Allow superuser group to do anything without password
  lineinfile:
    line: "%wheel ALL=(ALL) NOPASSWD:ALL"
    regexp: "^\\s*%wheel\\s+ALL\\s*="
    dest: /etc/sudoers
    state: present
    validate: "visudo -cf %s"
