- name: Uninstall redis/valkey packages
  package:
    name: "{{ redis_uninstalling_flavor }}"
    state: "absent"
  register: uninstall_redis_valkey_packages_result
  retries: 30
  until: uninstall_redis_valkey_packages_result is succeeded

- name: Install redis/valkey packages
  package:
    name: "{{ redis_package }}"
    state: "latest"
  notify:
    - Reload systemctl daemon
    - "Restart redis/valkey"
  register: install_redis_valkey_packages_result
  retries: 30
  until: install_redis_valkey_packages_result is succeeded
