- name: Uninstall redis packages
  package:
    name: >-
      {{ 'valkey' if redis_valkey_flavor == 'redis' else 'redis' }}
    state: "absent"
  notify:
    - Reload systemctl daemon
  ignore_errors: yes

- name: Install redis/valkey packages
  package:
    name: "{{ redis_package }}"
    state: "latest"
  notify:
    - Reload systemctl daemon
    - Restart {{ redis_daemon }}
