umask {{ '%04d' | format(mageops_cli_user_mask | default('0022') | int,) }}
if [ -f ~/.bashrc ] ; then
	. ~/.bashrc
fi

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"