- name: Get list of RDS instances
  amazon.aws.rds_instance_info:
    region: "{{ aws_region }}"
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  register: rds_instances_info

- name: Set list of rds instances
  set_fact:
    aws_rds_instances: "{{ rds_instances_info.instances }}"

- name: Filter rds instance list by tags
  set_fact:
    aws_rds_instances: "{{ aws_rds_instances | json_query(rds_instances_tag_filter_query) | default([]) }}"
  vars:
    rds_instances_tag_filter_query: "[?{% for k, v in aws_rds_facts_mysql_tags.items() -%}tags.{{ k }} == '{{ v }}'{% if not loop.last %} && {% endif %}{% endfor %}]"

- name: Filter out read replica instances
  set_fact:
    aws_rds_instances: >-
      {{
        aws_rds_instances
        | rejectattr('read_replica_source_db_instance_identifier', 'defined')
        | list
      }}

- name: Warn when more than one instance has been found
  debug:
    msg: |
      Warning! More than one matching rds instance found, using first one.
      Found: {{ aws_rds_instances | map(attribute='db_instance_identifier') | join(', ') }}
  when: aws_rds_instances | length > 1

- name: Set facts about project's rds instance
  set_fact:
    aws_rds_instance: "{{ aws_rds_instances | first }}"
    aws_rds_instance_id: "{{ (aws_rds_instances | first).db_instance_identifier }}"
    aws_rds_instance_host: "{{ (aws_rds_instances | first).endpoint.address }}"
  when: aws_rds_instances | length > 0

- name: Get facts about project's RDS cluster
  amazon.aws.rds_cluster_info:
    region: "{{ aws_region }}"
    db_cluster_identifier: "{{ aws_rds_instance.db_cluster_identifier }}"
  register: rds_cluster_info
  when:
    - aws_rds_instance is defined
    - (aws_rds_instance.db_cluster_identifier | default('', true) | string | length) > 0
    - aws_rds_instance.engine is match("^aurora")

- name: Set facts about project's RDS cluster
  set_fact:
    aws_rds_cluster: "{{ rds_cluster_info.clusters | first }}"
  when:
    - rds_cluster_info.clusters is defined
    - rds_cluster_info.clusters | length > 0

- name: Show project's RDS instance
  debug:
    msg: >-
      Found MySQL RDS instance: {{ aws_rds_instance.db_instance_identifier }} / {{ aws_rds_instance.endpoint.address }}
      ({{ aws_rds_instance.engine }} v{{ aws_rds_instance.engine_version }})
  when: aws_rds_instance is defined

- name: Show project's RDS cluster
  debug:
    msg: >-
      Found RDS cluster: {{ aws_rds_cluster.db_cluster_identifier }}
      ({{ aws_rds_cluster.engine }} v{{ aws_rds_cluster.engine_version }}, status: {{ aws_rds_cluster.status }})
  when: aws_rds_cluster is defined

- name: Set MySQL host to the RDS instance
  set_fact:
    mageops_mysql_host: "{{ aws_rds_instance.endpoint.address }}"
  when:
    - aws_rds_create | bool
    - aws_rds_instance is defined
    - aws_rds_instance.endpoint is defined
    - aws_rds_instance.endpoint.address is defined
